@startuml
class Door {
    + openDoorSprite : Sprite
    - spriteRenderer : SpriteRenderer
    - boxCollider : BoxCollider2D
    - Awake() : void
    + Unlock() : void
}
MonoBehaviour <|-- Door
IUnlockable <|-- Door
@enduml
