@startuml
class Lever {
    + doorToOpen : Door
    + leverActiveSprite : Sprite
    - spriteRenderer : SpriteRenderer
    - Awake() : void
    + Interact(interactor:GameObject) : void
    - OnTriggerEnter2D(other:Collider2D) : void
}
MonoBehaviour <|-- Lever
IInteractable <|-- Lever
@enduml
