@startuml
class AsyncOperation <<partial>> {
    <<internal>> m_Ptr : IntPtr
    - m_completeCallback : System.Action<AsyncOperation>
    <<internal>> InvokeCompletionEvent() : void
}
YieldInstruction <|-- AsyncOperation
@enduml
