@startuml
class ElementInfoAttribute <<sealed>> {
    + Order : int <<get>> <<set>>
    + Name : string <<get>> <<set>> = null
}
class CategoryInfoAttribute <<sealed>> {
    + Order : int <<get>> <<set>>
    + Name : string <<get>> <<set>> = null
}
Attribute <|-- ElementInfoAttribute
Attribute <|-- CategoryInfoAttribute
@enduml
