@startuml
class SimpleScript {
    - m_textMeshPro : TextMeshPro
    - <<const>> label : string = "The <#0050FF>count is: </color>{0:2&#125;"
    - m_frame : float
    - Start() : void
    - Update() : void
}
MonoBehaviour <|-- SimpleScript
@enduml
