@startuml
class TMP_TextSelector_A {
    - m_TextMeshPro : TextMeshPro
    - m_Camera : Camera
    - m_isHoveringObject : bool
    - m_selectedLink : int
    - m_lastCharIndex : int
    - m_lastWordIndex : int
    - Awake() : void
    - LateUpdate() : void
    + OnPointerEnter(eventData:PointerEventData) : void
    + OnPointerExit(eventData:PointerEventData) : void
}
MonoBehaviour <|-- TMP_TextSelector_A
IPointerEnterHandler <|-- TMP_TextSelector_A
IPointerExitHandler <|-- TMP_TextSelector_A
@enduml
