@startuml
class TMP_FrameRateCounter {
    + UpdateInterval : float = 5.0f
    - m_LastInterval : float = 0
    - m_Frames : int = 0
    + AnchorPosition : FpsCounterAnchorPositions
    - htmlColorTag : string
    - <<const>> fpsLabel : string = "{0:2&#125;</color> <#8080ff>FPS \n<#FF8000>{1:2&#125; <#8080ff>MS"
    - m_TextMeshPro : TextMeshPro
    - m_frameCounter_transform : Transform
    - m_camera : Camera
    - last_AnchorPosition : FpsCounterAnchorPositions
    - Awake() : void
    - Start() : void
    - Update() : void
    - Set_FrameCounter_Position(anchor_position:FpsCounterAnchorPositions) : void
}
enum FpsCounterAnchorPositions {
    TopLeft,
    BottomLeft,
    TopRight,
    BottomRight,
}
MonoBehaviour <|-- TMP_FrameRateCounter
TMP_FrameRateCounter +-- FpsCounterAnchorPositions
@enduml
