@startuml
class TMP_TextSelector_B {
    + TextPopup_Prefab_01 : RectTransform
    - m_TextPopup_RectTransform : RectTransform
    - m_TextPopup_TMPComponent : TextMeshProUGUI
    - <<const>> k_LinkText : string = "You have selected link <#ffff00>"
    - <<const>> k_WordText : string = "Word Index: <#ffff00>"
    - m_TextMeshPro : TextMeshProUGUI
    - m_Canvas : Canvas
    - m_Camera : Camera
    - isHoveringObject : bool
    - m_selectedWord : int
    - m_selectedLink : int
    - m_lastIndex : int
    - m_matrix : Matrix4x4
    - m_cachedMeshInfoVertexData : TMP_MeshInfo[]
    - Awake() : void
    - OnEnable() : void
    - OnDisable() : void
    - ON_TEXT_CHANGED(obj:Object) : void
    - LateUpdate() : void
    + OnPointerEnter(eventData:PointerEventData) : void
    + OnPointerExit(eventData:PointerEventData) : void
    + OnPointerClick(eventData:PointerEventData) : void
    + OnPointerUp(eventData:PointerEventData) : void
    - RestoreCachedVertexAttributes(index:int) : void
}
MonoBehaviour <|-- TMP_TextSelector_B
IPointerEnterHandler <|-- TMP_TextSelector_B
IPointerExitHandler <|-- TMP_TextSelector_B
IPointerClickHandler <|-- TMP_TextSelector_B
IPointerUpHandler <|-- TMP_TextSelector_B
@enduml
