@startuml
class TMPro_InstructionOverlay {
    + AnchorPosition : FpsCounterAnchorPositions
    - <<const>> instructions : string = "Camera Control - <#ffff00>Shift + RMB\n</color>Zoom - <#ffff00>Mouse wheel."
    - m_TextMeshPro : TextMeshPro
    - m_textContainer : TextContainer
    - m_frameCounter_transform : Transform
    - m_camera : Camera
    - Awake() : void
    - Set_FrameCounter_Position(anchor_position:FpsCounterAnchorPositions) : void
}
enum FpsCounterAnchorPositions {
    TopLeft,
    BottomLeft,
    TopRight,
    BottomRight,
}
MonoBehaviour <|-- TMPro_InstructionOverlay
TMPro_InstructionOverlay +-- FpsCounterAnchorPositions
@enduml
