@startuml
class VertexShakeA {
    + AngleMultiplier : float = 1.0f
    + SpeedMultiplier : float = 1.0f
    + ScaleMultiplier : float = 1.0f
    + RotationMultiplier : float = 1.0f
    - m_TextComponent : TMP_Text
    - hasTextChanged : bool
    - Awake() : void
    - OnEnable() : void
    - OnDisable() : void
    - Start() : void
    - ON_TEXT_CHANGED(obj:Object) : void
    - AnimateVertexColors() : IEnumerator
}
MonoBehaviour <|-- VertexShakeA
@enduml
