@startuml
class WarpTextExample {
    - m_TextComponent : TMP_Text
    + VertexCurve : AnimationCurve
    + AngleMultiplier : float = 1.0f
    + SpeedMultiplier : float = 1.0f
    + CurveScale : float = 1.0f
    - Awake() : void
    - Start() : void
    - CopyAnimationCurve(curve:AnimationCurve) : AnimationCurve
    - WarpText() : IEnumerator
}
MonoBehaviour <|-- WarpTextExample
@enduml
