@startuml
abstract class CharacterBaseController {
    + movementSpeed : float = 1f
    - # attackComponent : Attack <<get>>
    + contactFilter : ContactFilter2D
    - # health : IHealth <<get>>
    - # animator : Animator <<get>>
    - # isWalking : bool = false
    - # spriteRenderer : SpriteRenderer <<get>>
    - rb : Rigidbody2D <<get>>
    - <<readonly>> _collisions : List<RaycastHit2D>
    + TryMoving(direction:Vector2) : bool
    - MoveInDirection(direction:Vector2) : bool
}
MonoBehaviour <|-- CharacterBaseController
@enduml
