@startuml
class PlayerController {
    - movementInput : Vector2
    - FixedUpdate() : void
    - OnMove(movementValue:InputValue) : void
    + OnFire() : void
}
CharacterBaseController <|-- PlayerController
@enduml
